# Streamlit Secrets Configuration
# Add your RapidAPI key here
RAPIDAPI_KEY = "66a5941e36msh6019957b8d66a9bp18647djsnaefa60b20e43"

# MySQL Database Configuration
[mysql]
host = "localhost"
user = "root"
password = "Vasu@76652"
database = "cricketdb"
