# Streamlit Secrets Configuration
# Add your RapidAPI key here
RAPIDAPI_KEY = "375e06370bmshc971b281255e93dp10bf1cjsnb1df7908eb08"

# MySQL Database Configuration
[mysql]
host = "localhost"
user = "root"
password = "Vasu@76652"
database = "cricketdb"
