# Streamlit Secrets Configuration
# Add your RapidAPI key here
RAPIDAPI_KEY = "0b357a9ed8mshea2ef392d6abaf8p1b4e76jsn33cd0abc6a5e"

# MySQL Database Configuration
[mysql]
host = "localhost"
user = "root"
password = "Vasu@76652"
database = "cricketdb"
