# Streamlit Secrets Configuration
# Add your RapidAPI key here
RAPIDAPI_KEY = "468f9bf068msh1944388e73bd8a2p16d152jsn93f77fa19f2c"

# MySQL Database Configuration
[mysql]
host = "localhost"
user = "root"
password = "Vasu@76652"
database = "cricketdb"
